name: iam-pro-say

services:
  postgres:
    image: postgres
    container_name: iam-pro-say-postgres
    environment:
      POSTGRES_DB: iam-pro-say
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - iam-pro-say_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  iam-pro-say_postgres_data: